<?php

function topiclist()
{
    require "includes/dbh.inc.php";

    if ($_GET['category'] && $_GET['campus'] && $_GET['course']) {
        // Visible when logged in
        if (isset($_SESSION['userId']) && ($_SESSION['userVerified'] == "TRUE")) {
            echo '<div class="main-content"><div class="search-container">
            <form class="form-inline" action="search.php" method="POST">
                <div class="input-group">
                    <input type="text" class="form-control" name="search-string" placeholder="Search Topics" />
                    <div class="input-group-append">
                        <button name="search-submit" type="submit" class="btn btn-secondary">
                        <img src="./img/search.png">                        </button>
                    </div>
                </div>
            </form>
        </div>
                '; //Closing </div> for class = main-content can be found echoed out below after content has been generated by if statements and while loops

            if ($_GET['category']) {
                $userid = $_SESSION['userId'];
                $campusName = $_GET['campus'];
                $courseName = $_GET['course'];
                $categoryName = $_GET['category'];
                echo '<div class="breadcrumbs">
                <a href="index.php">FRONT PAGE</a>' . " > " . '
                <a href="course.php?campus=' . strtoupper($_GET['campus']) . '">' . strtoupper($_GET['campus']) . '</a>' . " > " . '
                <a href="category.php?campus=' . strtoupper($_GET['campus']) . "&course=" . strtoupper($_GET['course']) . '">' . strtoupper($_GET['course']) . '</a>' . " > " . strtoupper($_GET['category']) . '</div><div class="postnewtopic" onclick="topicnew()">
                <p>New Topic</p><img id="plus-icon-topic" src="img/plus.png" />
            </div>';

                // Select all entries from Topic table that contain specific parameters that have been taken from the URL in order to display the correct items for the page that has been selected
                $sql = "SELECT * FROM topics WHERE course='$courseName' AND campus='$campusName' AND category='$categoryName' ORDER BY recent DESC";
                $result = mysqli_query($conn, $sql);
                $resultCheck = mysqli_num_rows($result);

                if ($resultCheck > 0) {
                    // loop through entries and echo
                    while ($row = mysqli_fetch_assoc($result)) {
                        $topicid = $row['id'];

                        $time = $row['recent'];
                        $DS = date("M jS, Y", strtotime($time));
                        $TS = date("H:i", strtotime($time));
                        $title = substr($row['title'], 0, 50);

                        $sql2 = "SELECT * FROM comments WHERE topicid='$topicid' ORDER BY posted DESC";
                        $result2 = mysqli_query($conn, $sql2);
                        $resultCheck2 = mysqli_num_rows($result2);

                        echo '<div class="forum-category">' . '
                                <img class="topic-logo" src="uploads/' . $row['authorimg'] . '">
                               <div class="topic-title-desc">
                                    <a class="topic-title" href="topic.php?campus=' . $campusName . '&course=' . $courseName . '&category=' . $categoryName . '&id=' . $row['id'] . '">' . $title . '</a>
                                    <hr>
                                    <p></p>
                               </div>
                               <div class="topic-post-count">Replies:' . $resultCheck2 . '</div>
                               <h6 class="topic-post-recent" >' . "Most Recent<br>" . $DS . '<br>' . 'at ' . $TS . '</h6>
                              </div>';
                    }
                }
            }
            // hidden section that is only visible once user click New Topic Button
            echo ' <div  id="postnewtopic"  class="topic-container">
      <div class="closenewtopic" onclick="topicnew2()"><p>Close<img id="plus-icon-topic-close" src="img/plus.png"/></p></div>
        <form action="includes/topic.inc.php" id="topic-form" method="post">
        <input type="hidden" name="campus" value="' . $campusName . '">
    <input type="hidden" name="course" value="' . $courseName . '">
    <input type="hidden" name="category" value="' . $categoryName . '">
         <h1>Topic Title</h1><input type="text" name="topic-title" id="topictitle">
         <h1>Topic Content</h1>
         <textarea name="topic-body" id="topicbody" cols="30" rows="10"></textarea>
          <button type="submit" name="topic-submit">Post</button>
        </form>
      </div>
      <!-- Main Content -->';
            // hidden section end
        }
        // Visible when logged in
        // Visible when logged out
        else {
            echo '<div class="main-content-logout">
            <h1>You need to be logged in to view the forum</h1><br><h1>If you have registered, please check your email to verify your account</h1><br><a href="signup.php">Click here to register</a></div>
    </div>';
        }
    } else {
        header("Location: index.php");
    }

    // Visible when logged out

}
